/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as NewsRouteImport } from './routes/news'
import { Route as LiveRouteImport } from './routes/live'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as AgenciesRouteImport } from './routes/agencies'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VtuberSlugRouteImport } from './routes/vtuber.$slug'

const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenciesRoute = AgenciesRouteImport.update({
  id: '/agencies',
  path: '/agencies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VtuberSlugRoute = VtuberSlugRouteImport.update({
  id: '/vtuber/$slug',
  path: '/vtuber/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agencies': typeof AgenciesRoute
  '/directory': typeof DirectoryRoute
  '/live': typeof LiveRoute
  '/news': typeof NewsRoute
  '/submit': typeof SubmitRoute
  '/vtuber/$slug': typeof VtuberSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agencies': typeof AgenciesRoute
  '/directory': typeof DirectoryRoute
  '/live': typeof LiveRoute
  '/news': typeof NewsRoute
  '/submit': typeof SubmitRoute
  '/vtuber/$slug': typeof VtuberSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agencies': typeof AgenciesRoute
  '/directory': typeof DirectoryRoute
  '/live': typeof LiveRoute
  '/news': typeof NewsRoute
  '/submit': typeof SubmitRoute
  '/vtuber/$slug': typeof VtuberSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agencies'
    | '/directory'
    | '/live'
    | '/news'
    | '/submit'
    | '/vtuber/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agencies'
    | '/directory'
    | '/live'
    | '/news'
    | '/submit'
    | '/vtuber/$slug'
  id:
    | '__root__'
    | '/'
    | '/agencies'
    | '/directory'
    | '/live'
    | '/news'
    | '/submit'
    | '/vtuber/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgenciesRoute: typeof AgenciesRoute
  DirectoryRoute: typeof DirectoryRoute
  LiveRoute: typeof LiveRoute
  NewsRoute: typeof NewsRoute
  SubmitRoute: typeof SubmitRoute
  VtuberSlugRoute: typeof VtuberSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agencies': {
      id: '/agencies'
      path: '/agencies'
      fullPath: '/agencies'
      preLoaderRoute: typeof AgenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vtuber/$slug': {
      id: '/vtuber/$slug'
      path: '/vtuber/$slug'
      fullPath: '/vtuber/$slug'
      preLoaderRoute: typeof VtuberSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgenciesRoute: AgenciesRoute,
  DirectoryRoute: DirectoryRoute,
  LiveRoute: LiveRoute,
  NewsRoute: NewsRoute,
  SubmitRoute: SubmitRoute,
  VtuberSlugRoute: VtuberSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
